version: '3.3'

services:
  server:
    image: nginx
    container_name: dbbg-titel-liste-proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx:/etc/nginx
    depends_on:
      - frontend
    networks:
      - dbbg-titel-liste

  frontend:
    image: dbbg-titel-liste-frontend
    container_name: dbbg-titel-liste-frontend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - dbbg-titel-liste

networks:
  dbbg-titel-liste:
    external: true